### ISSUE TITLE
【游戏】角色异性伴侣系统

### ISSUE THREAD

**Issue by NEXTINDIE** [NEXTINDIE/Jurassic#13]
> **伴侣的效果加成**

1. 伴侣攻击免伤效果
1. 后代属性取父母平均值浮动（可变异）
1. 后代皮肤大概率遗传父母（可变异）
wait. 伴侣在5米范围抱窝时孵化加快
wait.伴侣在5米范围内增加防御效果

> **双方的后代如何进化？**

1.成为伴侣后雄性伴侣可以邀请雌性产卵（前提是雌性得有卵）;
1. 共同孕育的龙蛋均可以选择进化；
1. 父母双方皆可以选择邀请其它玩家孵化；
1. 死亡后巢穴中有100%蛋双方也可以选择复活；
1.蛋只能放在雌性建造的巢穴中进行孵化；

> **成为伴侣的方法？**

1. 异性同类恐龙可以邀请对方成为伴侣；
2. 直系亲属无法成为伴侣，近亲繁殖可能有惩罚；

> **解除伴侣的条件？**

1. 角色发生死亡；
1. 角色进化为新的恐龙；
1. 申请解除伴侣并被同意；
1. 伴侣解除后有1个小时的冷静期；

**Comment by 123456789020201** [comment]
我觉得两个性别不一样的龙下蛋行吗这个意见？ @NEXTINDIE
